name: Deploy to Play Store Internal

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deployInternal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Deploy to Play Internal
        shell: bash
        env:
          PLAY_STORE_JSON_KEY: ${{ secrets.PLAY_STORE_JSON_KEY}}
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_KEY_PSWD: ${{ secrets.KEYSTORE_KEY_PSWD }}
        run: |
          echo "$PLAY_STORE_JSON_KEY" > fastlane-api.json
          echo "$KEYSTORE_B64" | base64 --decode > keystore
          # 3. Recreate the properties file
          cat << 'EOF' > keystore.properties
          ${{ secrets.KEYSTORE_PROPERTIES }}
          EOF
          fastlane deployInternal
          rm -f fastlane-api.json keystore keystore.properties