name: Deploy to Play Store Internal

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deployInternal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Play Internal
        shell: bash
        env:
          PLAY_STORE_JSON_KEY_B64: ${{ secrets.PLAY_STORE_JSON_KEY_B64 }}
        run: |
          echo "$PLAY_STORE_JSON_KEY_B64" > fastlane-api.json
          fastlane deployInternal
          rm -f fastlane-api.json